dist: xenial
compiler: clang
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
matrix:
  include:
    - os: osx
      osx_image: xcode11.6
addons:
  apt:
    packages:
      - clang
      - pkg-config
bundler_args: --jobs=4 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" == "system" ]; then sudo gem install bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update bundler; fi
script:
  - git submodule update --init
  - bundle exec rake spec binary --trace
before_deploy:
  - bundle exec rake osx_varients --trace
deploy:
  provider: releases
  file_glob: true
  file: pkg/*.gem
  api_key:
    secure: "YM1qW1D52lN/lfQMTYABP9Cm9ZAj0BMpZb2g+rHhWaE+EykdJr4RYmC4O4hexXWO9bzIQXyI7Jg0PYMh/ZYzO8SZHs49VXOqjmSHHm5aGywclAtLtRxaLVWSe2vc68eFQNJTg/kRpgYzFpJ/5bUhfWhSD7yvHJ2gfPIF08T/F8iH7x21SmZH8TJk5DbSUBRaf8ZgLg4EdYj/o9QtpCW3Hbi1szw+PypQy1GcZGyM1vYZT7GUsO2Jrq6z7tHZgx4v7a5AWrCmmLCQhB+ktJ6u0bsv63Goflgm2oEdTPbFLup3odMhVE+iaRdTSU7gB0fjXidiMxjWhLtBdOaLd04eYk4elYy/ZUlIS0r8iFJYnXGnws59nsiS3gn1wpqAnVInE+IQYNbL0TNK01UJKVndJ9wgyqDenoE0Dd61nkaBGcVRxkIMsozaCioaKP0kmPvSsZrI3ysfqIgZo2ZGNNG3yq5v9cSB4XLQXc4vJjWQv4dgGgEFVzKEsdmcbp+uiySTIzq24Q9vBfKiSHD4DTbyrPIod3SVfnaqUerljVjAEBfZLyWtewp+yk3Eq9sQsghW/EruGb6EGw5z94NtsPUmgx/FwgsNVSIRueDlErwBJhLRq7jtSH5Zygnem7gYIStQa3sjHqKiCrfmWBNBnc0PU4xGM7n5qKYRx4uh/hcKRQo="
  skip_cleanup: true
  on:
    tags: true
    rvm: '2.7'
cache:
  bundler: true
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
    - nightpool@cybre.space
